"""empty message

Revision ID: f07b5d7299c6
Revises: 
Create Date: 2019-01-06 21:51:01.133450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07b5d7299c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_connection', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'api_connection', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_connection', type_='foreignkey')
    op.drop_column('api_connection', 'user_id')
    # ### end Alembic commands ###
